### ISSUE TITLE
Language icon

### ISSUE THREAD

**Issue by canweriotnow** [exercism/xelisp#19]
@kytrinyx I noticed some languages have icons on submissions... is there someplace I could upload an emacs icon (and what sixe/format) to appear on elisp track exercises?

**Comment by kytrinyx** [comment]
I completely forgot about language icons. Let me check and get back to you.

**Comment by canweriotnow** [comment]
awesome. emacs is easy, I'll try to find a cool lambda icon to use for scheme :)

**Comment by yurrriq** [comment]
Maybe [the Guile logo](https://www.gnu.org/software/guile/graphics/) would be cool.

**Comment by oubiwann** [comment]
I think the PLT-Scheme/MzScheme/Racket logo has dominated people's
consciousness for years as the visual identity for scheme (however
inaccurate that may actually be). I've certainly always been partial to
that one. Though the steal-your-face variation of PLT Scheme logo is pretty
sweet :-)

**Comment by yurrriq** [comment]
:+1: for that, in spite of the inaccuracy.
<img src="http://www.ece.northwestern.edu/~robby/logos/plt.svg" height=128 width=128>

The only reason I (Googled for and) suggested the Guile logo is the [getting started with Scheme][1] page has users install Guile. The PLT logo probably has friendlier usage rights anyway. ;)

[1]: http://help.exercism.io/getting-started-with-scheme.html

**Comment by canweriotnow** [comment]
@yurrriq The guile logo is awful :) I'd rather not use the Racket logo b/c it's misleading, and the colors kinda clash with exercism colors... I'm sure I can find a CC licensed logo on one of Steele or Sussman's old papers... maybe the eval/apply orb from the Wizard Book?

**Comment by yurrriq** [comment]
Agreed. I've never heard it called the Wizard Book, so thanks for that. I'm curious to know how to add icons to language tracks so we can add the LFE saucer.

**Comment by kytrinyx** [comment]
I found the images--they're all different sizes :/

https://github.com/exercism/exercism.io/tree/master/lib/app/public/img

anything from 128x128 to 256x256, it looks like.

**Comment by tejasbubane** [comment]
These are the small icons besides the submission name right? Are they used anywhere else? The sizes of these images seem to be unnecessarily large since the icon is scaled to 20x20 with CSS.

**Comment by kytrinyx** [comment]
Yeah. I'm hoping to get proper badges that we can use in a lot of places (the language pages, the profile--showing which language tracks you've submitted solutions to). https://github.com/exercism/exercism.io/issues/2357

**Comment by canweriotnow** [comment]
Resolved in https://github.com/exercism/exercism.io/pull/2647
