### ISSUE TITLE
Mention how to run all tests interactively

### ISSUE THREAD

**Issue by yurrriq** [exercism/xelisp#20]
[The guide][1] fails to mention that users can run all test interactively with this incantation:

```
M-x ert RET t
```

It might be good to mention (some of) the other [test selectors][2] too.

[1]: http://help.exercism.io/getting-started-with-elisp.html#running-tests
[2]: https://www.gnu.org/software/emacs/manual/html_node/ert/Test-Selectors.html#Test-Selectors

**Comment by kytrinyx** [comment]
+1 that's very handy!

**Comment by canweriotnow** [comment]
+1 Yeah, I gave a very basic overview of ert, I have some other docs to write this week, I'll try to do an update.

**Comment by yurrriq** [comment]
:tada:
