### ISSUE TITLE
Implement Emacs Lisp Exercises

### ISSUE THREAD

**Issue by canweriotnow** [exercism/xelisp#23]
This is a placeholder issue for keeping track of porting assignments to Lisp, or noting why they may not be applicable. (This list shamelessly stolen from https://github.com/exercism/xlisp/issues/23, which in turn was shamelessly stolen from https://github.com/exercism/xclojure/issues/1)

- [X] hello-world
- [X] bob
- [ ] word-count
- [X] anagram
- [ ] beer-song
- [ ] nucleotide-count
- [X] rna-transcription
- [X] point-mutations
- [ ] phone-number
- [ ] grade-school
- [X] robot-name
- [X] leap
- [ ] etl
- [ ] meetup
- [ ] space-age
- [ ] grains
- [X] gigasecond
- [ ] triangle
- [ ] scrabble-score
- [ ] roman-numerals
- [x] binary
- [ ] prime-factors
- [x] raindrops 
- [X] allergies
- [ ] strain
- [x] atbash-cipher
- ~~accumulate~~
- ~~bank-account~~
- [ ] crypto-square
- [ ] trinary
- [ ] sieve
- [ ] simple-cipher
- [ ] octal
- [ ] luhn
- [ ] pig-latin
- [ ] pythagorean-triplet @wobh
- [ ] series
- [X] difference-of-squares
- [ ] secret-handshake
- [ ] linked-list
- [ ] wordy
- [ ] hexadecimal
- [ ] largest-series-product
- [ ] kindergarden-garden
- [ ] binary-search-tree
- [ ] matrix
- [ ] robot-simulator
- [ ] nth-prime @wobh
- [ ] palindrome-products
- [ ] pascals-triangle @wobh
- [ ] say
- [ ] sum-of-multiples
- [ ] queen-attack
- [ ] saddle-points
- [ ] ocr-numbers

**Comment by kytrinyx** [comment]
Check out the "todo" key in this response: http://x.exercism.io/tracks/elisp -- that's the full list (always up to date with whatever is deployed).

**Comment by canweriotnow** [comment]
oooh, fancy! (and helpful!)

**Comment by yurrriq** [comment]
Thanks for the link, @kytrinyx! Should come in handy for xlfe too.

**Comment by kytrinyx** [comment]
I should probably document that in the brand spankin' new contrib document in x-common: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#maintaining-a-track

**Comment by canweriotnow** [comment]
I <3 this whole project and community :)

**Comment by yurrriq** [comment]
> I <3 this whole project and community :)

^ ditto

**Comment by kytrinyx** [comment]
Y'all just made my day!

**Comment by kytrinyx** [comment]
We have a new process that you can use to find exercises to implement.
You can read all about it [here](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track).

I'm closing this issue in favor of the process described in the Contributing guide linked to above.

Thanks!
