### ISSUE TITLE
README.org, etc.?

### ISSUE THREAD

**Issue by canweriotnow** [exercism/xelisp#6]
So, I guess this is a question for @kytrinyx, and kind of in two stages:

1. Any objection to moving `xelisp/README.md` to `xelisp/README.org` (i.e., org-mode instead of markdown)? Github renders .org files just like .md files, and emacs projects tend to use org-mode because, well, emacs users.
2. As lang-specific docs are moving from the central repo to the language track, what's the status of those docs needing to be rendered on http://exercism.io ? Do they need to remain markdown for web rendering? As a follow up, more long-term, thoughts on adding org-mode rendering capabilities to exercism.io alongside markdown? I forget the gem, but Github uses it.

**Comment by jchochli** [comment]
Are there really many Elisp projects with documentation in org format?

**Comment by canweriotnow** [comment]
@jchochli Yeah, I was surprised by how many... Also lots of Clojure and CL projects with docs in org format. I think once Github started supporting it, emacs hit `M-x party-mode`

**Comment by kytrinyx** [comment]
Go for it! It seems like a good choice in this case.

**Comment by canweriotnow** [comment]
@kytrinyx Cool! I'll check out the current state of rendering gems and report back when we get closer to that.

**Comment by wobh** [comment]
Of course, you could export to markdown.
